import re

files = [
    "2003/07/how-to-set-up-an-ftp-server-in-windows-server-2003-not/index.md",
    "2003/07/microsoft-identity-integration-server-2003-update/index.md",
    "2003/07/using-to-disambiguate-keywords-from-identifiers-in-c/index.md",
    "2003/08/associating-the-c-language-service-with-other-extensions/index.md",
    "2003/08/base-class-for-cloning-an-object-in-c/index.md",
    "2003/08/controlling-remote-access-via-policy/index.md",
    "2003/08/creating-iso-images-with-nero-5-5-express/index.md",
    "2003/08/dual-monitors-for-my-laptop/index.md",
    "2003/08/hiding-your-email-address-on-a-web-page/index.md",
    "2003/08/role-access-security-in-net/index.md",
    "2003/08/scripting-with-c/index.md",
    "2003/08/security-library/index.md",
    "2003/08/some-things-are-easier-in-c/index.md",
    "2003/09/c-foreach-with-arrays/index.md",
    "2003/09/dont-use-generics-simply-to-bury-a-cast-operation/index.md",
    "2003/09/implementing-an-interface-multiple-times-in-one-class-using-generics/index.md",
    "2003/09/more-on-configuration-management-application-block-for-net-from-microsoft-patterns-practices-2/index.md",
    "2003/09/the-trouble-with-checked-exceptions/index.md",
    "2003/09/web-services-versus-remoting-versus-enterprise-services/index.md",
    "2003/10/software-fashion/index.md",
    "2003/11/a-great-windows-tip-site/index.md",
    "2003/11/background-spelling-for-avalon-text-boxes/index.md",
    "2003/11/keywords-vs-contextual-keywords/index.md",
    "2003/11/syntax-inconsistencies-between-c-specification-and-pdc-whidbey-build/index.md",
    "2003/12/changing-short-file-names/index.md",
    "2003/12/explicit-vs-non-explicit-interface-implementation-and-the-clr-internals/index.md",
    "2004/02/cs1668-warning-as-error-invalid-search-path/index.md",
    "2004/02/muti-monitor-support-tools/index.md",
    "2004/02/short-iterations-are-key-in-soa/index.md",
    "2004/03/google-stuff-you-might-not-know-about/index.md",
    "2004/04/beware-of-inequalities-with-floating-point-types/index.md",
    "2004/04/sourcesafe/index.md",
    "2004/04/synchronizing-folders-revisited/index.md",
    "2004/04/word-keyboard-shortcut-for-clear-formatting/index.md",
    "2004/05/marking-items-in-shared-libraries-as-obsolete/index.md",
    "2004/06/comparison-operators-not-behaving-equally/index.md",
    "2004/06/creating-a-toggle-anchor-lock-macro-for-images-in-word/index.md",
    "2004/06/defining-a-component-in-software-engineering/index.md",
    "2005/01/arrghhh-the-overwhelming-differentiator-between-web-and-rich-clients/index.md",
    "2005/01/unit-testing-console-inputoutput/index.md",
    "2005/02/ambiguous-overloading-with-generics/index.md",
    "2005/02/converting-command-line-string-to-args-using-commandlinetoargvw-api/index.md",
    "2005/02/fun-overloading-with-generics/index.md",
    "2005/02/modifying-prop-a-visual-studio-2005-ide-expansions-template/index.md",
    "2005/02/providing-a-test-method-expansion-template/index.md",
    "2005/02/system-windows-forms-timer-vs-system-threading-timer-vs-system-timers-timer/index.md",
    "2005/03/calling-web-services-using-basic-authentication/index.md",
    "2005/03/missing-guidance-for-fixing-architecture-without-re-writing/index.md",
    "2005/04/accessibility-of-new-types-in-visual-studio-2005/index.md",
    "2005/04/whidbey-beta-2-posted/index.md",
    "2005/05/nullable-and-the-struct-constraint-in-vs-net-beta-2/index.md",
    "2005/05/registering-a-string-of-code-as-an-apparent-delegate-listener-2/index.md",
    "2005/06/class-and-new-constraints-with-generic-methods/index.md",
    "2005/06/converting-a-class-library-to-a-vsts-test-project/index.md",
    "2005/06/flagsattribute-and-bitwise-or-without-the-flagsattribute/index.md",
    "2005/06/launching-the-asp-net-development-server-from-the-command-line/index.md",
    "2005/06/msh-and-sdkvars-bat/index.md",
    "2005/06/msh-monad-the-good-the-bad-and-the-ugly/index.md",
    "2005/06/reducing-casts-using-generics-without-casting-internally/index.md",
    "2005/06/removing-adds-from-internet-explorer/index.md",
    "2005/06/retrieving-the-short-name-of-a-file/index.md",
    "2005/07/how-to-detect-virtual-machine-execution/index.md",
    "2005/07/using-marshal-getdelegateforfunctionpointer-to-execute-assembler-with-managed-code/index.md",
    "2005/08/build-status-using-lava-lamps-by-ken-nichols/index.md",
    "2005/09/avoiding-the-prefix-from-current-directory-files-in-msh-2/index.md",
    "2005/09/notes-on-some-c-3-0-features-that-make-linq-possible/index.md",
    "2005/09/the-basics-of-system-io-ports-serialport/index.md",
    "2005/10/dont-use-the-system-diagnostics-assert-methods-unless/index.md",
    "2005/10/unsuccessfully-defining-a-wrapper-for-debug-assert/index.md",
    "2005/11/mutating-the-immutable-string/index.md",
    "2006/02/robocopy-standard-on-windows-vista/index.md",
    "2006/02/windows-communication-foundation-with-windows-vista-and-uac/index.md",
    "2006/03/microsofts-biztalk-ebusiness-suite-adapter/index.md",
    "2006/05/using-line-of-business-apis-from-middleware/index.md",
    "2006/07/chapter-sample-mastering-generics/index.md",
    "2006/07/net-3-0-road-show/index.md",
    "2006/08/amazone-runs-a-special-on-essential-c/index.md",
    "2006/08/microsoft-tools-team-readies-rosario/index.md",
    "2006/09/creating-a-tfs-work-item-from-powershell/index.md",
    "2006/10/essential-c-chapter-on-msdn-c-developer-center/index.md",
    "2006/12/associating-a-work-item-to-a-changeset-after-checking-in/index.md",
    "2007/02/the-internals-of-foreach/index.md",
    "2007/04/skrbl-the-ultimate-in-real-time-electronic-whiteboarding/index.md",
    "2007/08/biztalk-fatal-error-x1001-unknown-system-exception/index.md",
    "2007/08/biztalk-lob-whitepapers/index.md",
    "2007/08/biztalk-smtp-adapter-is-missing-bcc-functionality/index.md",
    "2007/08/ftp-pgp-and-me/index.md",
    "2007/08/introduction/index.md",
    "2007/08/pgp-pipeline-component/index.md",
    "2007/08/pgp-pipeline-component-v1-1/index.md",
    "2007/08/search-and-replace-pipeline-component/index.md",
    "2007/08/the-curse-of-the-dollar-sign/index.md",
    "2007/12/enumerating-process-getprocesses-fails-on-vista/index.md",
    "2008/06/a-bunch-of-windows-administration-command-line-tools/index.md",
    "2008/08/data-connection-string-for-a-csv-file-on-vsts-data-driven-test/index.md",
    "2008/09/turning-off-ie-enhanced-security-from-the-command-line/index.md",
    "2008/10/my-favorite-windows-7-features/index.md",
    "2008/10/vss-to-tfs-conversion-error/index.md",
    "2008/11/dynamically-typed-objects-with-c-4-0/index.md",
    "2008/11/windows7-boots-to-black/index.md",
    "2008/12/sql-server-2008-install-nightmare/index.md",
    "2008/12/unattended-installation-of-team-foundation-server-2008-on-windows-2008-with-sql-server-2008/index.md",
    "2010/02/the-microsoft-net-framework-software-architecture/index.md",
    "2010/04/an-intellitechture-service-overview-for-the-utility-industry/index.md",
    "2010/04/parallel-for-where-i-does-not-go-to-i/index.md",
    "2010/10/configuring-windows-smtp-server-on-windows-2008-for-relay/index.md",
    "2011/05/work-item-search-in-visual-studio-vnext/index.md",
    "2011/09/management-verses-leadership/index.md",
    "2011/09/project-management-versus-project-leadership/index.md",
    "2011/09/sql-server-2008-sp2-uninstall-fails/index.md",
    "2011/09/subscribing-to-tfs-alerts-with-tfs-power-tools-alerts-explorer-3/index.md",
    "2011/12/enterprise-service-bus/index.md",
    "2012/02/storyboarding-in-visual-studio-11-with-lorem-ipsum-auto-expand/index.md",
    "2012/02/transitioning-between-sprintsiterations-with-tfs/index.md",
    "2012/02/visual-studio-11-ide-productivity-improvements/index.md",
    "2012/02/visual-studio-11-search-everywhere/index.md",
    "2012/03/leveraging-the-callermembername-attribute-for-inotifypropertychangedinotifypropertychangings-events/index.md",
    "2012/03/new-attributes-for-tracelogging-information-in-net-4-5/index.md",
    "2012/03/turning-on-continuous-testing-in-visual-studio-11/index.md",
    "2012/06/removing-duplicate-entries-from-path/index.md",
    "2013/08/loadfrom-exception-an-attempt-was-made-to-load-a-program-with-an-incorrect-format/index.md",
    "2013/10/relative-paths-for-visual-studio-generic-tests/index.md",
    "2014/01/c-6-0-simplifies-clarifies-condenses-code-msdn/index.md",
    "2014/05/c6-language-preview-msdn/index.md",
    "2014/08/declaration-expressions-in-c-6-0/index.md",
    "2014/08/exception-handling-improvements-in-c-6-0/index.md",
    "2014/08/static-using-statement-in-c-6-0/index.md",
    "2014/10/new-and-improved-c6-msdn/index.md",
    "2014/11/mscorelib-classes-that-work-with-using-static-in-c-6-0/index.md"
    # "2015/01/the-cil-of-c-6-0s-string-interpolation/index.md",
    # "2015/03/code-reviews/index.md",
    # "2015/04/suspend-and-resume-in-visual-studio-using-tfs/index.md",
    # "2015/06/deploying-windows-services-with-psake-and-web-deploy/index.md",
    # "2015/06/dynamically-changing-cell-databehavior-within-a-kendo-grid/index.md",
    # "2015/06/entityframework-update-database-fails-with-invalid-directory-on-url/index.md",
    # "2015/07/design-process-and-creative-control/index.md",
    # "2015/07/downloading-attachments-from-tfs/index.md",
    # "2015/07/when-to-use-and-not-use-var-in-c/index.md",
    # "2015/07/youre-agile-why-are-you-using-project/index.md",
    # "2015/08/building-a-logger-using-caller-info-attributes-part-1/index.md",
    # "2015/08/communication/index.md",
    # "2015/08/scrum-from-a-qa-perspective/index.md",
    # "2015/08/should-your-scrum-team-assign-story-points-to-a-spike/index.md",
    # "2015/08/using-the-kendo-grid-in-an-unorthodox-manner/index.md",
    # "2015/08/validating-a-business-idea/index.md",
    # "2015/09/creating-an-nlog-wrapper-that-logs-to-azure-table-storage/index.md",
    # "2015/09/exceptionguidelinesforcsharp/index.md",
    # "2015/09/how-i-became-a-vim-rockstar-in-visual-studio/index.md",
    # "2015/09/integrations-and-the-canonical-model/index.md",
    # "2015/09/unit-testing-with-mocks/index.md",
    # "2015/09/web-config-transforms/index.md",
    # "2015/09/writing-secure-software-part-1/index.md",
    # "2015/10/devops-metrics/index.md",
    # "2015/10/how-to-form-a-hypothesis-and-why-you-should-care/index.md",
    # "2015/10/improving-unit-tests-with-automocker/index.md",
    # "2015/11/csharp-exception-handling/index.md",
    # "2015/11/reducing-boilerplate-code-with-resharper-templates/index.md",
    # "2015/12/designing-c-7/index.md",
    # "2015/12/display-a-custom-tooltip-at-the-mouse-position-on-a-large-wpf-control/index.md",
    # "2015/12/scrum-from-a-qa-perspective-part-2/index.md",
    # "2015/12/writing-secure-software-part-2/index.md",
    # "2016/01/custom-model-binding-in-asp-net-core-1-0/index.md",
    # "2016/01/intellitect-is-offering-asp-net-core-training/index.md",
    # "2016/01/self-hosted-integration-testing-of-odata-and-webapi/index.md",
    # "2016/01/troubleshooting-asp-net-5-dnx-bower-npm-gulp-and-related-tools/index.md",
    # "2016/01/using-nightly-builds-for-asp-net-core-1-0/index.md",
    # "2016/02/essential-net-configuration-in-net-core-msdn/index.md",
    # "2016/03/building-single-page-applications-spa-with-the-journey-framework/index.md",
    # "2016/03/implementing-a-custom-ilogger-with-exception-handling-for-net-core/index.md",
    # "2016/03/making-sense-of-assemblyversion-numbers/index.md",
    # "2016/03/multibinding-in-xamarin-forms/index.md",
    # "2016/04/essential-net-logging-with-net-core/index.md",
    # "2016/04/oracle-data-provider-for-net/index.md",
    # "2016/04/xamarin-forms-enumbindablepicker/index.md",
    # "2016/05/json-serializer-that-doesnt-serialize-other-properties-if-deleted-is-true/index.md",
    # "2016/05/native-animation-effects-in-xamarin-forms/index.md",
    # "2016/05/net-core-dependency-injection/index.md",
    # "2016/06/command-line-processing-with-net-core-1-0/index.md",
    # "2016/06/locking-a-block-of-code-with-an-integer/index.md",
    # "2016/07/upgrading-asp-net-core-to-rtm/index.md",
    # "2016/07/visual-studio-2015-net-core-tooling/index.md",
    # "2016/08/displaying-deploymentbuild-date-web-pages/index.md",
    # "2016/08/making-unit-testing-easier/index.md",
    # "2016/08/using-powershells-invoke-restmethod-access-vsts-odata/index.md",
    # "2016/09/command-line-processing-dotnet-core-1-msdn/index.md",
    # "2016/09/creating-fody-addin/index.md",
    # "2016/10/deterministic-finalization/index.md",
    # "2016/10/finalizers-in-csharp/index.md",
    # "2016/10/generalized-async-return-types/index.md",
    # "2016/10/implicitconversionwithcsharp7deconstructors/index.md",
    # "2016/10/powershell-getting-better-msdn/index.md",
    # "2016/11/csharp-7-msdn/index.md",
    # "2017/01/essential-msbuild-overview-net-tooling-msdn/index.md",
    # "2017/01/staying-logged-across-azure-app-service-swap/index.md",
    # "2017/01/upgrading-sql-server-localdb/index.md",
    # "2017/02/moving-quickly-among-branches-with-powershell-dynamic-parameters/index.md",
    # "2017/02/publishing-a-nuget/index.md",
    # "2017/04/c-foreach-internals-custom-iterators-with-yield-msdn/index.md",
    # "2017/04/fix-system-valuetuple-error/index.md",
    # "2017/05/feasibility-test-automation/index.md",
    # "2017/05/how-i-installed-software-on-a-server/index.md",
    # "2017/05/unit-testing-xamarin-forms/index.md",
    # "2017/06/custom-iterators-with-yield-msdn/index.md",
    # "2017/07/csharp7-tuples-explained/index.md",
    # "2017/07/deploying-app-squirrel/index.md",
    # "2017/07/updating-sql-database-use-temporal-tables-entity-framework-migration/index.md",
    # "2017/09/fix-your-git-credentials-in-4-steps/index.md",
    # "2017/09/getting-started-model-view-viewmodel-mvvm-pattern-using-windows-presentation-framework-wpf/index.md",
    # "2017/10/deciding-write-wrapper/index.md",
    # "2017/10/timers-prior-to-async-await/index.md",
    # "2017/12/convert-utc-local-time-daylight-savings-support-power-bi/index.md",
    # "2018/01/employee-spotlight-brian-jones/index.md",
    # "2018/01/intellitect-today-smart-meters/index.md",
    # "2018/02/csharp-8-nullable-reference-types-msdn/index.md",
    # "2018/03/ildasm-with-net-core/index.md",
    # "2018/03/overidingobjectusingtuple/index.md",
    # "2018/04/asp-net-core-dynamic-routing-with-constraints/index.md",
    # "2018/04/async-await-windows-ui/index.md",
    # "2018/04/data-demystified-strengthening-your-enterprise/index.md",
    # "2018/04/devops-presentation-reality-or-fiction/index.md",
    # "2018/04/intellitect-today-streamline-work-reduce-enterprise-costs/index.md",
    # "2018/04/interfacing-multithreading-patterns/index.md",
    # "2018/04/machine-learning-can-save-lives/index.md",
    # "2018/04/powershell-write-error-without-writing-stack-trace/index.md",
    # "2018/06/c-tuples-break-guidelines-msdn/index.md",
    # "2018/07/core-values/index.md",
    # "2018/07/elegant-innovative-excellence-c-sharp/index.md",
    # "2018/07/employee-spotlight-kelly-adams/index.md",
    # "2018/07/getting-started-material-design-in-xaml/index.md",
    # "2018/07/intellitect-today-fasttrack-your-success/index.md",
    # "2018/07/start-devops-journey/index.md",
    # "2018/07/tech-consultants-demystified/index.md",
    # "2018/08/material-design-in-xaml-dialog-host/index.md",
    # "2018/08/powershell-script-change-history-file/index.md",
    # "2018/09/debugging-method-return-values/index.md",
    # "2018/09/solve-any-year-game-puzzle/index.md",
    # "2018/09/tic-tac-toe-game/index.md",
    # "2018/10/how-to-contribute-to-microsoft-open-source-software-projects-msdn/index.md",
    # "2018/10/quickly-configure-asp-net-core-api-to-work-with-vue-cli-3/index.md",
    # "2018/11/c-sharp-8-video/index.md",
    # "2018/11/xamarin-forms-video/index.md",
    # "2018/12/demystified-buy-or-build/index.md",
    # "2018/12/employee-spotlight-andrew-scott/index.md",
    # "2018/12/innovation-hiring/index.md",
    # "2018/12/intellitect-today-migrate-asp-net-core/index.md",
    # "2018/12/securing-web-api-dotnetcore-2-2/index.md",
    # "2019/01/android-apk-level-phonegap/index.md",
    # "2019/02/demystified-design/index.md",
    # "2019/02/intellitect-today-teaching-at-eastern/index.md",
    # "2019/02/platypus-awards/index.md",
    # "2019/03/bug-testing-isolation-variables/index.md",
    # "2019/03/docker-postgresql/index.md",
    # "2019/03/docker-scaffold/index.md",
    # "2019/03/parse-command-line/index.md",
    # "2019/04/decoupling-csharp-testable/index.md",
    # "2019/04/video-asp-net-core-2-2/index.md",
    # "2019/04/video-machine-learning-including-agile-machine-learning/index.md",
    # "2019/05/demystified-agile/index.md",
    # "2019/05/employee-spotlight-grant-erickson/index.md",
    # "2019/05/intellitect-today-new-building/index.md",
    # "2019/05/scrum-master-check-in/index.md",
    # "2019/07/dotnet-5/index.md",
    # "2019/07/selenium-chrome-csharp/index.md",
    # "2019/08/cyber-physical-office/index.md",
    # "2019/08/employee-spotlight-mike-curn/index.md",
    # "2019/08/intellitect-today-simplifying-cloud-migrations/index.md",
    # "2019/08/kubernetes/index.md",
    # "2019/08/terraform-azure-infrastructure/index.md",
    # "2019/09/check-for-null-not-null/index.md",
    # "2019/09/enter-vsdevshell-powershell/index.md",
    # "2019/10/exponential-technology-revolution-slides/index.md",
    # "2019/10/microsoft-mvp-two/index.md",
    # "2019/10/visual-studio-2019-update-slides/index.md",
    # "2019/11/azure-serverless-video/index.md",
    # "2019/11/client-spotlight-thanks/index.md",
    # "2019/11/demystified-microsoft-development-technologies/index.md",
    # "2019/11/exiftool-people-tag-recovery/index.md",
    # "2019/11/exponential-technology-revolution/index.md",
    # "2019/11/intellitect-today-scavenger-fun/index.md",
    # "2019/11/net-core-3-video/index.md",
    # "2019/11/visual-studio-2019-video/index.md",
    # "2019/11/xamarin-forms-4-video/index.md",
    # "2020/01/netsdk1004-compile-error/index.md",
    # "2020/02/azure-devops-nugets/index.md",
    # "2020/02/demystified-next-gen-tech/index.md",
    # "2020/02/intellitect-today-open-house/index.md",
    # "2020/02/transition-netcore3/index.md",
    # "2020/05/demystifyed-online-presentation/index.md",
    # "2020/05/intellitect-today-leadership-covid-19/index.md",
    # "2020/06/oracle-sql-database/index.md",
    # "2020/06/vue-cli-net-core-3-1/index.md",
    # "2020/07/demystified-azure-pipeline-vsix-extension/index.md",
    # "2020/07/legacy-system-threading/index.md",
    # "2020/08/dare-to-lead/index.md",
    # "2020/08/intellitect-today-blood-drive-2020/index.md",
    # "2020/08/intellitects-new-normal-pandemic/index.md",
    # "2020/09/delivery-drone/index.md",
    # "2020/09/over-five-gallons-of-blood/index.md",
    # "2020/11/employee-spotlight-kevin-bost/index.md",
    # "2020/11/intellitect-today-creating-intelliwiki/index.md",
    # "2020/12/power-bi-data-importation/index.md",
    # "2021/01/powershell-dsc/index.md",
    # "2021/01/streaming-online-presentation-obs/index.md",
    # "2021/01/virtual-greenscreen-obs/index.md",
    # "2021/02/passwordless-authentication-azure-sql/index.md",
    # "2021/02/unit-testing-shift-left/index.md",
    # "2021/03/power-bi-data-compression/index.md",
    # "2021/03/video-devcontainers/index.md",
    # "2021/03/video-essential-c-sharp-9/index.md",
    # "2021/04/demystifying-requirements-gathering/index.md",
    # "2021/04/employee-spotlight-meg-woodford/index.md",
    # "2021/04/intellitect-today-passionate-hard-work/index.md",
    # "2021/04/net-5-video/index.md",
    # "2021/05/clone-aad-windows-10/index.md",
    # "2021/05/debugging/index.md",
    # "2021/05/modern-system-commandline/index.md"
]
list = []
for file in files:
    with open(file, encoding="utf8") as markdownFile:
        markdown = markdownFile.read()
        image = file.replace("/index.md", "")
        githubPath = "https://raw.githubusercontent.com/worseTyler/MarkdownBlogs/main/" + image
        # markdown = re.sub(r'images/', githubPath + '/images/', markdown)
        # markdown = re.sub(r'(?s)^---.+---\n', '', markdown)
        strings = re.findall(r'[#\n]+# .+', markdown)

        for string in strings:
            id = string.lower()
            # id = id.replace(".net", "net")
            id = id.replace(" ", "-")
            id = id.replace("...", "-")
            id = id.replace("?", "")
            id = id.replace("\n", "")
            id = id.replace("#", "")
            id = id.replace("'", "-")
            id = id.replace("{}", "-")
            id = id.replace("[]", "-")
            id = id.replace(":", "")
            id = id.replace(".", "")
            id = id.replace(",", "")
            id = id.replace("!", "")
            id = id.replace("(", "")
            id = id.replace(")", "")
            id = id.replace("[", "")
            id = id.replace("]", "")
            id = id.replace("<", "")
            id = id.replace(">", "")
            id = id.replace("&", "")
            id = id.replace("---", "-")
            id = id.replace("--", "-")

            replacementString = string + " {#h" + id + "}"
            print(replacementString)
        
        markdownFile.close()
        # writeFile = open(file, encoding="utf8", mode="w")
        # writeFile.write(markdown)
        # writeFile.close()


            # id = id.replace(" ", "-")
            # id = id.replace("...", "-")
            # id = id.replace("?", "")
            # id = id.replace("'", "-")
            # id = id.replace("{}", "-")
            # id = id.replace("[]", "-")
            # id = id.replace(":", "")
            # id = id.replace(".", "")
            # id = id.replace(",", "")
            # id = id.replace("!", "")
            # id = id.replace("(", "")
            # id = id.replace(")", "")
            # id = id.replace("[", "")
            # id = id.replace("]", "")
            # id = id.replace("<", "")
            # id = id.replace(">", "")
            # id = id.replace("&", "")